# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/newpolaris/Projects/IrradianceEnvMap

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/newpolaris/Projects/IrradianceEnvMap

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/newpolaris/Projects/IrradianceEnvMap/CMakeFiles /Users/newpolaris/Projects/IrradianceEnvMap/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/newpolaris/Projects/IrradianceEnvMap/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iem

# Build rule for target.
iem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iem
.PHONY : iem

# fast build rule for target.
iem/fast:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/build
.PHONY : iem/fast

#=============================================================================
# Target rules for targets named glsw

# Build rule for target.
glsw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glsw
.PHONY : glsw

# fast build rule for target.
glsw/fast:
	$(MAKE) -f CMakeFiles/glsw.dir/build.make CMakeFiles/glsw.dir/build
.PHONY : glsw/fast

external/glsw/bstrlib.o: external/glsw/bstrlib.c.o

.PHONY : external/glsw/bstrlib.o

# target to build an object file
external/glsw/bstrlib.c.o:
	$(MAKE) -f CMakeFiles/glsw.dir/build.make CMakeFiles/glsw.dir/external/glsw/bstrlib.c.o
.PHONY : external/glsw/bstrlib.c.o

external/glsw/bstrlib.i: external/glsw/bstrlib.c.i

.PHONY : external/glsw/bstrlib.i

# target to preprocess a source file
external/glsw/bstrlib.c.i:
	$(MAKE) -f CMakeFiles/glsw.dir/build.make CMakeFiles/glsw.dir/external/glsw/bstrlib.c.i
.PHONY : external/glsw/bstrlib.c.i

external/glsw/bstrlib.s: external/glsw/bstrlib.c.s

.PHONY : external/glsw/bstrlib.s

# target to generate assembly for a file
external/glsw/bstrlib.c.s:
	$(MAKE) -f CMakeFiles/glsw.dir/build.make CMakeFiles/glsw.dir/external/glsw/bstrlib.c.s
.PHONY : external/glsw/bstrlib.c.s

external/glsw/glsw.o: external/glsw/glsw.c.o

.PHONY : external/glsw/glsw.o

# target to build an object file
external/glsw/glsw.c.o:
	$(MAKE) -f CMakeFiles/glsw.dir/build.make CMakeFiles/glsw.dir/external/glsw/glsw.c.o
.PHONY : external/glsw/glsw.c.o

external/glsw/glsw.i: external/glsw/glsw.c.i

.PHONY : external/glsw/glsw.i

# target to preprocess a source file
external/glsw/glsw.c.i:
	$(MAKE) -f CMakeFiles/glsw.dir/build.make CMakeFiles/glsw.dir/external/glsw/glsw.c.i
.PHONY : external/glsw/glsw.c.i

external/glsw/glsw.s: external/glsw/glsw.c.s

.PHONY : external/glsw/glsw.s

# target to generate assembly for a file
external/glsw/glsw.c.s:
	$(MAKE) -f CMakeFiles/glsw.dir/build.make CMakeFiles/glsw.dir/external/glsw/glsw.c.s
.PHONY : external/glsw/glsw.c.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/tools/Logger.o: src/tools/Logger.cpp.o

.PHONY : src/tools/Logger.o

# target to build an object file
src/tools/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/src/tools/Logger.cpp.o
.PHONY : src/tools/Logger.cpp.o

src/tools/Logger.i: src/tools/Logger.cpp.i

.PHONY : src/tools/Logger.i

# target to preprocess a source file
src/tools/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/src/tools/Logger.cpp.i
.PHONY : src/tools/Logger.cpp.i

src/tools/Logger.s: src/tools/Logger.cpp.s

.PHONY : src/tools/Logger.s

# target to generate assembly for a file
src/tools/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/src/tools/Logger.cpp.s
.PHONY : src/tools/Logger.cpp.s

src/tools/TCamera.o: src/tools/TCamera.cpp.o

.PHONY : src/tools/TCamera.o

# target to build an object file
src/tools/TCamera.cpp.o:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/src/tools/TCamera.cpp.o
.PHONY : src/tools/TCamera.cpp.o

src/tools/TCamera.i: src/tools/TCamera.cpp.i

.PHONY : src/tools/TCamera.i

# target to preprocess a source file
src/tools/TCamera.cpp.i:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/src/tools/TCamera.cpp.i
.PHONY : src/tools/TCamera.cpp.i

src/tools/TCamera.s: src/tools/TCamera.cpp.s

.PHONY : src/tools/TCamera.s

# target to generate assembly for a file
src/tools/TCamera.cpp.s:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/src/tools/TCamera.cpp.s
.PHONY : src/tools/TCamera.cpp.s

src/tools/Timer.o: src/tools/Timer.cpp.o

.PHONY : src/tools/Timer.o

# target to build an object file
src/tools/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/src/tools/Timer.cpp.o
.PHONY : src/tools/Timer.cpp.o

src/tools/Timer.i: src/tools/Timer.cpp.i

.PHONY : src/tools/Timer.i

# target to preprocess a source file
src/tools/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/src/tools/Timer.cpp.i
.PHONY : src/tools/Timer.cpp.i

src/tools/Timer.s: src/tools/Timer.cpp.s

.PHONY : src/tools/Timer.s

# target to generate assembly for a file
src/tools/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/src/tools/Timer.cpp.s
.PHONY : src/tools/Timer.cpp.s

src/tools/gltools.o: src/tools/gltools.cpp.o

.PHONY : src/tools/gltools.o

# target to build an object file
src/tools/gltools.cpp.o:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/src/tools/gltools.cpp.o
.PHONY : src/tools/gltools.cpp.o

src/tools/gltools.i: src/tools/gltools.cpp.i

.PHONY : src/tools/gltools.i

# target to preprocess a source file
src/tools/gltools.cpp.i:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/src/tools/gltools.cpp.i
.PHONY : src/tools/gltools.cpp.i

src/tools/gltools.s: src/tools/gltools.cpp.s

.PHONY : src/tools/gltools.s

# target to generate assembly for a file
src/tools/gltools.cpp.s:
	$(MAKE) -f CMakeFiles/iem.dir/build.make CMakeFiles/iem.dir/src/tools/gltools.cpp.s
.PHONY : src/tools/gltools.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... iem"
	@echo "... glsw"
	@echo "... external/glsw/bstrlib.o"
	@echo "... external/glsw/bstrlib.i"
	@echo "... external/glsw/bstrlib.s"
	@echo "... external/glsw/glsw.o"
	@echo "... external/glsw/glsw.i"
	@echo "... external/glsw/glsw.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/tools/Logger.o"
	@echo "... src/tools/Logger.i"
	@echo "... src/tools/Logger.s"
	@echo "... src/tools/TCamera.o"
	@echo "... src/tools/TCamera.i"
	@echo "... src/tools/TCamera.s"
	@echo "... src/tools/Timer.o"
	@echo "... src/tools/Timer.i"
	@echo "... src/tools/Timer.s"
	@echo "... src/tools/gltools.o"
	@echo "... src/tools/gltools.i"
	@echo "... src/tools/gltools.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

